# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e55ab06ec953a397fab70a1365008ee1efbcd0a8f5470ba37acf75219f72bf6a5339ba3b7a522002accc00e4ba926a08d1890246210a68cd1209c4ac24565c

test:
  secret_key_base: 13eca3754b8195ae646c06f712c2ad49fea4e5e54aefc06ee11bd3d92ccdd6dd864d52049e4c693cf365be333c0705c279207e6a431d0134ccdb488c10a26182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
